### ISSUE TITLE
Invalid index error when changing `number_of_broker_nodes` variable

### ISSUE THREAD

**Issue by vsimon** [cloudposse/terraform-aws-msk-apache-kafka-cluster#17]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

Invalid index error when changing `number_of_broker_nodes` variable from 2 to 4. (The # of AZ's is 2 instead of 3 like the example but I'm guessing this is not the underlying problem).

```
Error: Invalid index

  on .terraform/modules/msk_cluster/main.tf line 152, in module "hostname":
 152:   records = [split(":", local.bootstrap_brokers_combined_list[count.index])[0]]
    |----------------
    | count.index is 2
    | local.bootstrap_brokers_combined_list is list of string with 2 elements

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/msk_cluster/main.tf line 152, in module "hostname":
 152:   records = [split(":", local.bootstrap_brokers_combined_list[count.index])[0]]
    |----------------
    | count.index is 3
    | local.bootstrap_brokers_combined_list is list of string with 2 elements

The given key does not identify an element in this collection value.

Releasing state lock. This may take a few moments...
```

## Expected Behavior

The plan/apply should succeed and additional nodes added to the internal "hostname" module.

## Steps to Reproduce
1. Have a config is similar to the complete/example but with 2 AZ's instead of 3. Set `number_of_broker_nodes` to 2.
2. terraform apply
3. Change `number_of_broker_nodes` from 2 to 4. Run plan.
4. terraform plan

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.33.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

**Comment by gitbrad** [comment]
I've encountered this issue as well, using module version 0.5.2. @vsimon were you able to find a workaround?

**Comment by vsimon** [comment]
No workaround found yet unfortunately :(

**Comment by sekka1** [comment]
+1

**Comment by ashwini-hopin** [comment]
+1 .

**Comment by nitrocode** [comment]
@ashwini-hopin @sekka1 @vsimon @gitbrad Try using this pr branch and see if it works for you

```hcl
module "kafka" {
  source = "https://github.com/cloudposse/terraform-aws-msk-apache-kafka-cluster.git?ref=module-hostname-count"

  # your arguments
}
```

**Comment by ashwini-hopin** [comment]
@nitrocode  Amazing ( pr #29 ) fixed my issue. However, just discovered that the broker endpoints is outputting only 3 brokers even though the cluster runs 4 brokers

**Comment by ashwini-hopin** [comment]
I reached out to AWS support to understand why only 3 endpoints are being outputted. Here's the response from them. In case it helps someone,

********************
In order to get more insight, I reached out to our MSK service team and they informed me that this is an expected behavior that both UI and getBootstrapBrokers API gives maximum 3 brokers as the output as you will only need a maximum of 3 broker node details to successfully connect or programmatically connect to the MSK cluster at any given moment. The broker node details presented may randomly change as part of the connection string  when retrieving the broker node connection string, alternatively you can still connect to any other available broker nodes on your cluster or make use of, as a connection string (Thus, you will only ever need a maximum of 3 broker nodes to ensure high availability when connecting, producing or consuming from the cluster).

Having said that, only 3 brokers will be listing in bootstrap list irrespective of the number of brokers configured in the cluster and this is by design. However, all brokers will be part of the cluster.

you can make use of the 'list-nodes' API [1] , with paginate or no-paginate option to control returned results when retrieving all the broker node details on your cluster. See sample command below:

> aws kafka list-nodes --cluster-arn arn:aws:kafka:us-east-1:accountID:cluster/demo-cluster-1/6357e0b2-0e6a-4b86-a0b4-70df934c2e31-5 --no-paginate

[1] https://docs.aws.amazon.com/cli/latest/reference/kafka/list-nodes.html 

****************************
