### ISSUE TITLE
Rolling update cluster when instance type is changed

### ISSUE THREAD

**Issue by ferrangali** [cloudposse/terraform-aws-msk-apache-kafka-cluster#32]
## Describe the Feature

MSK cluster gets completely recreated (destroyed and then created) when instance type is changed.

## Expected Behavior

I would expect the cluster to be rolling-updated, without downtime (assuming cluster has the proper size, 3 brokers, 3 AZ, partitions replicated).
AWS supports this feature, and it works either with the CLI and the console.
https://aws.amazon.com/about-aws/whats-new/2021/01/amazon-msk-now-supports-the-ability-to-change-the-size-or-family/?nc1=h_ls

## Alternatives Considered

Edit brokers in AWS console. But that is something I would like to avoid.

**Comment by nitrocode** [comment]
@ferrangali we use the [aws_msk_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster) resource and if this doesn't support it yet then there isn't anything we can do until that is resolved in the aws provider.

See the open issues here

* https://github.com/hashicorp/terraform-provider-aws/issues/17332
* https://github.com/hashicorp/terraform-provider-aws/issues?q=is%3Aissue+is%3Aopen+aws_msk_cluster

If this issue isn't there then I'd suggest creating one.

Hmm... looking more at the code

https://github.com/hashicorp/terraform-provider-aws/blob/1b0103ec6f4dacc3599c25cea81fbdc653f759c4/internal/service/kafka/cluster.go#L86-L89

I don't see a `ForceNew` there. Perhaps this will be fixed by upgrading the provider to 3.x
